controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hoverboard_base_controller:
      type: diff_drive_controller/DiffDriveController